stages:
  data_ingestion:
    cmd: python src/data_ingestion.py 
    deps: 
      - src/data_ingestion.py

    outs: 
      - data/raw
  
  pre-processing:
    cmd: python src/pre-processing.py
    deps: 
      - data/raw
      - src/pre-processing.py
    outs:
      - data/intrim
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/intrim
      - src/feature_engineering.py
    outs:
      - data/processed_data
  model_selection:
    cmd: python src/model_selection.py
    deps:
      - data/processed_data
      - src/model_selection.py
    outs:
      - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - models/model.pkl
      - src/model_evaluation.py
    metrics:
      - reports/metrics.json



      